### ISSUE TITLE
[BUG] Force Close on hitting enemies in caves with any conjurer spell. Seed:ZXV-QYS-TVF

### ISSUE THREAD

**Issue by 0xlne** [TrashboxBobylev/Summoning-Reincarnated#10]
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: HONOR
Device: HNFCP
Model: FCP-AN10
Manufacturer: HONOR
Product: FCP-AN10
SDK: 34
Release: 14

***** APP INFO 
Version: ReInc-0.4.0-738c3e5
Installed On: 2024-10-07 19:30:28
Updated On: 2024-11-17 02:07:22
Current Date: 2024-11-26 11:18:05

***** ERROR LOG 
java.lang.ClassCastException: com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfLivingEarth cannot be cast to com.shatteredpixel.shatteredpixeldungeon.items.magic.ConjurerSpell
	at com.shatteredpixel.shatteredpixeldungeon.items.magic.ConjurerSpell.afterZap(ConjurerSpell.java:210)
	at com.shatteredpixel.shatteredpixeldungeon.items.magic.ConjurerSpell$1$1.call(ConjurerSpell.java:31)
	at com.shatteredpixel.shatteredpixeldungeon.sprites.MissileSprite.onComplete(MissileSprite.java:8)
	at com.watabou.noosa.tweeners.Tweener.onComplete(Tweener.java:5)
	at com.watabou.noosa.tweeners.Tweener.update(Tweener.java:44)
	at com.watabou.noosa.Group.update(Group.java:25)
	at com.watabou.noosa.Group.update(Group.java:25)
	at com.watabou.noosa.Scene.update(Scene.java:1)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.PixelScene.update(PixelScene.java:21)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene.update(GameScene.java:41)
	at com.watabou.noosa.Game.update(Game.java:41)
	at com.watabou.noosa.Game.step(Game.java:23)
	at com.watabou.noosa.Game.render(Game.java:71)
	at z.j.onDrawFrame(AndroidGraphics.java:225)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1586)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1283)

***** END OF LOG *****

**Comment by 0xlne** [comment]
Another one; same seed. Started apoearing in the caves:

***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: HONOR
Device: HNFCP
Model: FCP-AN10
Manufacturer: HONOR
Product: FCP-AN10
SDK: 34
Release: 14

***** APP INFO 
Version: ReInc-0.4.0-738c3e5
Installed On: 2024-10-07 19:30:28
Updated On: 2024-11-17 02:07:22
Current Date: 2024-11-27 21:55:26

***** ERROR LOG 
java.lang.ClassCastException: com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfLivingEarth cannot be cast to com.shatteredpixel.shatteredpixeldungeon.items.magic.ConjurerSpell
	at com.shatteredpixel.shatteredpixeldungeon.items.magic.ConjurerSpell.afterZap(ConjurerSpell.java:210)
	at com.shatteredpixel.shatteredpixeldungeon.items.magic.ConjurerSpell$1$1.call(ConjurerSpell.java:31)
	at com.shatteredpixel.shatteredpixeldungeon.sprites.MissileSprite.onComplete(MissileSprite.java:8)
	at com.watabou.noosa.tweeners.Tweener.onComplete(Tweener.java:5)
	at com.watabou.noosa.tweeners.Tweener.update(Tweener.java:44)
	at com.watabou.noosa.Group.update(Group.java:25)
	at com.watabou.noosa.Group.update(Group.java:25)
	at com.watabou.noosa.Scene.update(Scene.java:1)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.PixelScene.update(PixelScene.java:21)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene.update(GameScene.java:41)
	at com.watabou.noosa.Game.update(Game.java:41)
	at com.watabou.noosa.Game.step(Game.java:23)
	at com.watabou.noosa.Game.render(Game.java:71)
	at z.j.onDrawFrame(AndroidGraphics.java:225)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1586)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1283)



***** END OF LOG *****
