### ISSUE TITLE
[BUG] Force Close on starting ascension from defeating YD

### ISSUE THREAD

**Issue by 0xlne** [TrashboxBobylev/Summoning-Reincarnated#11]
Yog Dzewa defeated, amulet recovered.
Force close is encountered on trying to exit YD's floor to go back to F24.
Entering the game from the save results in the same force close.

***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: HONOR
Device: HNFCP
Model: FCP-AN10
Manufacturer: HONOR
Product: FCP-AN10
SDK: 34
Release: 14

***** APP INFO 
Version: ReInc-0.4.1-b327444
Installed On: 2024-10-07 19:30:28
Updated On: 2024-12-06 03:44:41
Current Date: 2024-12-22 15:51:01

***** ERROR LOG 
java.lang.RuntimeException: fatal error occurred while moving between floors. Seed:4078775368212 depth:24
	at com.shatteredpixel.shatteredpixeldungeon.scenes.InterlevelScene.update(InterlevelScene.java:493)
	at com.watabou.noosa.Game.update(Game.java:41)
	at com.watabou.noosa.Game.step(Game.java:23)
	at com.watabou.noosa.Game.render(Game.java:71)
	at z.j.onDrawFrame(AndroidGraphics.java:225)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1586)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1283)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
	at java.lang.Class.isAssignableFrom(Class.java:824)
	at com.shatteredpixel.shatteredpixeldungeon.actors.buffs.AscensionChallenge.statModifier(AscensionChallenge.java:75)
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob.onAdd(Mob.java:13)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Actor.add(Actor.java:7)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Actor.add(Actor.java:1)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Actor.init(Actor.java:26)
	at com.shatteredpixel.shatteredpixeldungeon.Dungeon.switchLevel(Dungeon.java:78)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.InterlevelScene.ascend(InterlevelScene.java:57)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.InterlevelScene.access$1200(InterlevelScene.java:1)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.InterlevelScene$5.run(InterlevelScene.java:46)

***** END OF LOG *****

**Comment by 0xlne** [comment]
Seed
![Uploading Screenshot_20241222_155412_com_trashboxbobylev_resummoningpixeldungeon_AndroidLaun.jpg…]()

**Comment by TrashboxBobylev** [comment]
Fixed in 0.4.2.
