### ISSUE TITLE
[BUG] dwarven summon on Rank II corrupting demon eye (mob in demon halls) leads to game crash

### ISSUE THREAD

**Issue by Hubi1111111** [TrashboxBobylev/Summoning-Reincarnated#12]
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: Redmi
Device: sweet
Model: M2101K6G
Manufacturer: Xiaomi
Product: sweet_eea
SDK: 30
Release: 11

***** APP INFO 
Version: ReInc-0.4.1-b327444
Installed On: 2024-12-24 10:21:06
Updated On: 2024-12-24 10:21:06
Current Date: 2024-12-26 07:08:27

***** ERROR LOG 
java.lang.NullPointerException: Attempt to read from field 'int com.shatteredpixel.shatteredpixeldungeon.actors.hero.Hero.lvl' on a null object reference
    at com.shatteredpixel.shatteredpixeldungeon.actors.buffs.AllyBuff.affectAndLoot(AllyBuff.java:58)
    at com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfCorruption.corruptEnemy(WandOfCorruption.java:29)
    at com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfCorruption.onZap(WandOfCorruption.java:227)
    at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.minions.Wizard.zap(Wizard.java:70)
    at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.minions.Wizard.onZapComplete(Wizard.java:1)
    at com.shatteredpixel.shatteredpixeldungeon.sprites.WizardSprite$1.call(WizardSprite.java:7)
    at com.shatteredpixel.shatteredpixeldungeon.effects.MagicMissile.update(MagicMissile.java:45)
    at com.watabou.noosa.Group.update(Group.java:25)
    at com.watabou.noosa.Group.update(Group.java:25)
    at com.watabou.noosa.Scene.update(Scene.java:1)
    at com.shatteredpixel.shatteredpixeldungeon.scenes.PixelScene.update(PixelScene.java:21)
    at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene.update(GameScene.java:41)
    at com.watabou.noosa.Game.update(Game.java:41)
    at com.watabou.noosa.Game.step(Game.java:23)
    at com.watabou.noosa.Game.render(Game.java:71)
    at z.j.onDrawFrame(AndroidGraphics.java:225)
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1577)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

***** END OF LOG *****

**Comment by TrashboxBobylev** [comment]
Fixed in 0.4.2.
