### ISSUE TITLE
[BUG] Force Close

### ISSUE THREAD

**Issue by 0xlne** [TrashboxBobylev/Summoning-Reincarnated#3]
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: Xiaomi
Device: zizhan
Model: 22061218C
Manufacturer: Xiaomi
Product: zizhan
SDK: 33
Release: 13

***** APP INFO 
Version: ReInc-0.3.2-a3a04e8
Installed On: 2024-07-29 21:16:27
Updated On: 2024-07-29 21:16:27
Current Date: 2024-07-30 11:56:59

***** ERROR LOG 
java.lang.NullPointerException: Attempt to read from null array
	at com.shatteredpixel.shatteredpixeldungeon.Dungeon.findPassable(Dungeon.java:10)
	at com.shatteredpixel.shatteredpixeldungeon.Dungeon.findPassable(Dungeon.java:1)
	at com.shatteredpixel.shatteredpixeldungeon.Dungeon.findPath(Dungeon.java:3)
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob.getCloser(Mob.java:353)
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob$Wandering.continueWandering(Mob.java:15)
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob$Wandering.act(Mob.java:41)
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob.act(Mob.java:118)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Actor.process(Actor.java:127)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene$2.run(GameScene.java:1)

***** END OF LOG *****
![Screenshot_2024-07-30-11-56-12-015_com trashboxbobylev resummoningpixeldungeon](https://github.com/user-attachments/assets/03228586-3d36-4c93-aa9b-60702689c63a)

**Comment by 0xlne** [comment]
Another one in a new game; happens right after attacking the crab:
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: Xiaomi
Device: zizhan
Model: 22061218C
Manufacturer: Xiaomi
Product: zizhan
SDK: 33
Release: 13

***** APP INFO 
Version: ReInc-0.3.2-a3a04e8
Installed On: 2024-07-29 21:16:27
Updated On: 2024-07-29 21:16:27
Current Date: 2024-07-30 17:33:31

***** ERROR LOG 
java.lang.NullPointerException: Attempt to read from null array
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob.canSee(Mob.java:3)
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob.chooseEnemy(Mob.java:138)
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob$Hunting.act(Mob.java:147)
	at com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Mob.act(Mob.java:118)
	at com.shatteredpixel.shatteredpixeldungeon.actors.Actor.process(Actor.java:127)
	at com.shatteredpixel.shatteredpixeldungeon.scenes.GameScene$2.run(GameScene.java:1)



***** END OF LOG *****

![Screenshot_2024-07-30-17-34-17-676_com trashboxbobylev resummoningpixeldungeon](https://github.com/user-attachments/assets/de40b97a-f020-44ed-8445-09187bd8c9e9)
